apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-dedicated-server
spec:
  template:
    spec:
      containers:
        - name: squad-dedicated-server
          env:
            - name: SERVER_NAME
              value: "An example of a Squad Dedicated Server"
            - name: MODS
              value: "(100000 1000001)"
            - name: FIXEDMAXPLAYERS
              value: "80"
            - name: FIXEDMAXTICKRATE
              value: "60"
            - name: RANDOM
              value: "FIRST"
