apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-dedicated-server
  labels:
    app: squad-dedicated-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-dedicated-server
  template:
    metadata:
      labels:
        app: squad-dedicated-server
    spec:
      volumes:
        - name: squad-dedicated-server-data
          persistentVolumeClaim:
            claimName: squad-dedicated-server-pvc
      containers:
        - name: squad-dedicated-server
          image: cm2network/squad:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "1"
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - test -f /home/steam/squad-dedicated/SquadGame/Saved/Logs/SquadGame.log
            initialDelaySeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 7787
              protocol: UDP
            - containerPort: 27165
              protocol: UDP
            - containerPort: 15000
              protocol: UDP
            - containerPort: 21114
              protocol: UDP
          env:
            - name: SERVER_NAME
              value: "Squad Dedicated Server"
            - name: MODS
              value: "()"
            - name: PORT
              value: "7787"
            - name: QUERYPORT
              value: "27165"
            - name: BEACONPORT
              value: "15000"
            - name: RCONPORT
              value: "21114"
            - name: FIXEDMAXPLAYERS
              value: "100"
            - name: FIXEDMAXTICKRATE
              value: "50"
            - name: RANDOM
              value: "ALWAYS"
          volumeMounts:
            - mountPath: /home/steam/squad-dedicated/
              name: squad-dedicated-server-data
