apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squad-dedicated-server-pvc
  labels:
    app: squad-dedicated-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
