apiVersion: v1
kind: Service
metadata:
  name: squad-dedicated-server-service
spec:
  selector:
    app: squad-dedicated-server
  ports:
    - port: 7787
      targetPort: 7787
      protocol: UDP
    - port: 27165
      targetPort: 27165
      protocol: UDP
    - port: 15000
      targetPort: 15000
      protocol: UDP
    - port: 21114
      targetPort: 21114
      protocol: UDP
